import {
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { customers } from "./customers";
import { resourceProvider, resources } from "./resources";

// How a provider cost was obtained: pulled from a billing API, or entered by hand.
export const costSource = pgEnum("cost_source", ["metered", "fixed"]);

// How a resource draws its cost: a fixed monthly amount, or a weighted share of a
// provider cost pool (e.g. a container's share of the one Hetzner box invoice).
export const allocationMode = pgEnum("allocation_mode", ["fixed", "weighted"]);

// A pool of provider spend for a period (e.g. "Hetzner web.example.test — 2026-06").
// Weighted allocations divide a pool across resources; fixed allocations don't need one.
export const providerCosts = pgTable(
  "provider_costs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    provider: resourceProvider("provider").notNull(),
    period: text("period").notNull(), // 'YYYY-MM'
    label: text("label").notNull(),
    source: costSource("source").notNull().default("fixed"),
    amountCents: integer("amount_cents").notNull(),
    currency: text("currency").notNull().default("EUR"),
    // When set, this is a host-scoped pool (e.g. a Hetzner box invoice) that the
    // auto-allocator splits across only that host's containers. Null = the pool
    // is provider-scoped (today's account-level behavior, e.g. AWS).
    resourceId: text("resource_id").references(() => resources.id, { onDelete: "set null" }),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [unique("provider_costs_provider_period_label_unq").on(t.provider, t.period, t.label)],
);

// One cost assignment per resource per period. fixed -> amountCents; weighted ->
// weight * the linked pool's amount.
export const costAllocations = pgTable(
  "cost_allocations",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    resourceId: text("resource_id")
      .notNull()
      .references(() => resources.id, { onDelete: "cascade" }),
    period: text("period").notNull(),
    mode: allocationMode("mode").notNull(),
    amountCents: integer("amount_cents"),
    weight: doublePrecision("weight"),
    providerCostId: text("provider_cost_id").references(() => providerCosts.id, {
      onDelete: "cascade",
    }),
    // True when generated by the usage-weighted auto-allocator. Manual edits set
    // this false so the auto-allocator leaves them alone.
    auto: boolean("auto").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [unique("cost_allocations_resource_period_unq").on(t.resourceId, t.period)],
);

// One-off adjustment to what a customer is charged in a period (a credit, a setup
// fee, a correction). Recurring prices live in contract_positions.
export const customerPricing = pgTable(
  "customer_pricing",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    period: text("period").notNull(),
    amountCents: integer("amount_cents").notNull(),
    currency: text("currency").notNull().default("EUR"),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [unique("customer_pricing_customer_period_unq").on(t.customerId, t.period)],
);

// How often a contract position bills.
export const billingInterval = pgEnum("billing_interval", ["monthly", "yearly", "once"]);

// What a customer buys: the recurring price model. One row per sold item
// ("Hosting site.example.test", "5 Postfächer"), optionally tied to the resource it
// covers. The charge for a period is the sum of positions active in that period
// (yearly spread over twelve months, once only in its start period) plus any
// one-off adjustment in customer_pricing for that exact period.
export const contractPositions = pgTable(
  "contract_positions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "cascade" }),
    resourceId: text("resource_id").references(() => resources.id, { onDelete: "set null" }),
    label: text("label").notNull(),
    quantity: doublePrecision("quantity").notNull().default(1),
    unitPriceCents: integer("unit_price_cents").notNull(),
    interval: billingInterval("interval").notNull().default("monthly"),
    startsPeriod: text("starts_period").notNull(), // 'YYYY-MM', inclusive
    endsPeriod: text("ends_period"), // 'YYYY-MM', inclusive; null = open-ended
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [index("contract_positions_customer_idx").on(t.customerId)],
);
